.\" Copyright 2019 Google LLC
.\"
.\" Licensed under the Apache License, Version 2.0 (the "License");
.\" you may not use this file except in compliance with the License.
.\" You may obtain a copy of the License at
.\"
.\"     https://www.apache.org/licenses/LICENSE-2.0
.\"
.\" Unless required by applicable law or agreed to in writing, software
.\" distributed under the License is distributed on an "AS IS" BASIS,
.\" WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
.\" See the License for the specific language governing permissions and
.\" limitations under the License.
.TH SOR 1 2019-09-16
.SH NAME
sor \- combine shell predicates with logical or
.SH SYNOPSIS
.B sor
.RB [\| \-0 \]
.IR SNIPPET ...
.SH DESCRIPTION
Read paths from standard input. For each path, evaluate each argument as a
.BR bash (1)
snippet with the path as the first argument. Print the path to standard output
if any of the snippets exits with status 0.
.SH OPTIONS
.TP
\fB\-0\fP, \fB\-\-null\fP
Filenames are terminated using the null character \fB\\0\fP instead of
newlines, for both input and output.
Suitable for use with \fBwalk \-0\fP.
.TP
\fB\-\-help\fP
Print a summary of the usage of \fBsor\fP and exit.
.SH EXAMPLE
.EX
walk /etc | sor 'test -f'
.EE
.SH "SEE ALSO"
.BR find (1),
.BR walk (1)
